/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frames;

import com.mycompany.motorphgui2.Employees;
import com.mycompany.motorphgui2.Staff;
import com.mycompany.motorphgui2.CredentialsManager;
import com.mycompany.motorphgui2.LoginResult;
import com.mycompany.motorphgui2.Permission;
import com.mycompany.motorphgui2.Role;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author DAVID
 */
public class CreateUserLogin extends javax.swing.JDialog {
     private Role currentUserRole;

    /**
     * Creates new form CreateUserLogin
     */
    public CreateUserLogin(javax.swing.JFrame parent, boolean modal) {
//        this.setModalityType(ModalityType.APPLICATION_MODAL);
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeIDTF = new javax.swing.JPasswordField();
        employeeIDLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        usernameTF = new javax.swing.JTextField();
        addUserButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeIDTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeIDTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(employeeIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 184, -1));

        employeeIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeIDLabel.setText("EmployeeID:");
        getContentPane().add(employeeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setText("Username:");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        passwordTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordTF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 184, -1));

        usernameTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null));
        getContentPane().add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 184, -1));

        addUserButton.setBackground(new java.awt.Color(204, 204, 204));
        addUserButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addUserButton.setText("Add");
        addUserButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserButton(evt);
            }
        });
        getContentPane().add(addUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 60, 30));

        CloseButton.setBackground(new java.awt.Color(204, 204, 204));
        CloseButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CloseButton.setText("Close");
        CloseButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButtonclose(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 60, 30));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gray White Creative Motorcycle Present Flyer (1).jpg"))); // NOI18N
        jLabel20.setToolTipText("");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserButton
             // Retrieve input values from text fields
    String username = usernameTF.getText().trim();
    char[] password = passwordTF.getPassword();; // Securely get password as string
    String employeeID = employeeIDTF.getText().trim();
    this.currentUserRole = LoginResult.getCurrentUser().getRole();
    

        // Validate input fields
        if (username.isEmpty() || password.length == 0 || employeeID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // No perm
         if (!currentUserRole.hasPermission(currentUserRole, Permission.AddLoginUser)) {
        JOptionPane.showMessageDialog(this, "You do not have permission to add users!", "Permission Denied", JOptionPane.ERROR_MESSAGE);
        return;
    }

        try {
            CredentialsManager credentialsManager = new CredentialsManager();
            credentialsManager.CreateUser(username, password, employeeID, currentUserRole);
            JOptionPane.showMessageDialog(this, "User added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error saving user: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addUserButton

    private void CloseButtonclose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButtonclose
        dispose();
    }//GEN-LAST:event_CloseButtonclose

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateUserLogin dialog = new CreateUserLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JPasswordField employeeIDTF;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
