/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frames;
import com.mycompany.motorphgui2.Employees;
import com.mycompany.motorphgui2.LoginResult;
import com.mycompany.motorphgui2.Permission;
import com.mycompany.motorphgui2.Role;
import com.mycompany.motorphgui2.Staff;
import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;




/**
 *
 * @author DAVID
 */
public class LeaveViewFrame extends javax.swing.JDialog {

    private Role currentUserRole;
    private Staff staff;
    /**
     * Creates new form LeaveViewFrame
     */
   public LeaveViewFrame(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.currentUserRole = LoginResult.getCurrentUser().getRole();

        staff = new Staff();
        String filename = "Leave Application.csv";

        try {
            leaveStatusTable.setModel(staff.leaveStatus(filename));
        } catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error loading leave data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        leaveStatusTable = new javax.swing.JTable();
        approveButton = new javax.swing.JButton();
        denyButton1 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(204, 204, 204));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonClose(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 94, 30));

        leaveStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Leave ID", "Employee ID", "Last Name", "Start Date", "End Date", "Number of Days", "Type of Leave ", "Reason", "Status"
            }
        ));
        leaveStatusTable.setAutoscrolls(false);
        leaveStatusTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        leaveStatusTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        leaveStatusTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(leaveStatusTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 740, 292));

        approveButton.setBackground(new java.awt.Color(204, 204, 204));
        approveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        approveButton.setText("Approve");
        approveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(approveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 94, 30));

        denyButton1.setBackground(new java.awt.Color(204, 204, 204));
        denyButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        denyButton1.setText("Deny");
        denyButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        denyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(denyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 94, 30));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red and Beige Geometric Style Custom Motorcycle Garage Presentation.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonClose(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonClose
        dispose();
    }//GEN-LAST:event_closeButtonClose

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        updateLeaveStatus("Approved");
    }//GEN-LAST:event_approveButtonActionPerformed

    private void denyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyButton1ActionPerformed
       updateLeaveStatus("Denied");
    }//GEN-LAST:event_denyButton1ActionPerformed

    private void updateLeaveStatus(String status) {
        if (!currentUserRole.hasPermission(currentUserRole, Permission.ProcessLeave)) {
                JOptionPane.showMessageDialog(this, "You do not have permission to process leave.", "Access Denied", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        
        
    int selectedRow = leaveStatusTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row.", "Selection Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String leaveID = leaveStatusTable.getValueAt(selectedRow, 0).toString(); // Get Leave ID
    List<String[]> csvData = new ArrayList<>();
    String fileName = "Leave Application.csv";

    try (CSVReader csvReader = new CSVReader(new FileReader(fileName))) {
        String[] line;

        while ((line = csvReader.readNext()) != null) {
            if (line[0].equals(leaveID)) {
                line[9] = status; // Update the "Application Status" column
            }
            csvData.add(line);
        }
    } catch (IOException | CsvValidationException ex) {
        Logger.getLogger(LeaveViewFrame.class.getName()).log(Level.SEVERE, null, ex);
    }

    // Write updated data back to CSV
    try (CSVWriter csvWriter = new CSVWriter(new FileWriter(fileName))) {
        csvWriter.writeAll(csvData);
    } catch (IOException ex) {
        Logger.getLogger(LeaveViewFrame.class.getName()).log(Level.SEVERE, null, ex);
    }

    JOptionPane.showMessageDialog(this, "Leave status updated to: " + status, "Update Successful", JOptionPane.INFORMATION_MESSAGE);

    // Refresh the table after updating
    updateLeaveStatusTable();
}
     
 
    private void updateLeaveStatusTable() {
    String fileName = "Leave Application.csv"; // Filename for leave records

    try {
        // Create an instance of Staff to call leaveStatus
        Staff staff = new Staff();

        // Populate the table with updated data
        leaveStatusTable.setModel(staff.leaveStatus(fileName));

    } catch (IOException | CsvValidationException ex) {
        Logger.getLogger(LeaveViewFrame.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error updating leave status table.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Corrected: Pass JDialog instead of JFrame
                LeaveViewFrame dialog = new LeaveViewFrame(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton denyButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable leaveStatusTable;
    // End of variables declaration//GEN-END:variables
}
