/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import com.mycompany.motorphgui2.Employees;
import com.mycompany.motorphgui2.Staff;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * 
 */
public class LeaveFrame extends javax.swing.JDialog {

    /**
     * Creates new form ViewRecordFrame
     */
    
    
    public LeaveFrame(Staff staff) throws IOException, FileNotFoundException, CsvValidationException {
        initComponents();
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        
        String filename = "Remaining_Leave.csv";
        employeeNumberTF.setText(staff.getEmployeeNumber());
        firstNameTF.setText(staff.getFirstName());
        lastNameTF.setText(staff.getLastName());
        leaveTable.setModel( staff.leaveDetails(filename));
        dateFiledTF.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));
        
    }

    private LeaveFrame(){
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        leaveTable = new javax.swing.JTable();
        leaveDetailsPanel = new javax.swing.JPanel();
        LeaveDetailsLabel = new javax.swing.JLabel();
        employeeNumberLabel = new javax.swing.JLabel();
        typeOfLeaveLabel = new javax.swing.JLabel();
        leaveTypeCB = new javax.swing.JComboBox<>();
        numberOfDaysLabel = new javax.swing.JLabel();
        daysCB = new javax.swing.JComboBox<>();
        employeeNumberTF = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        leaveDurationPanel = new javax.swing.JPanel();
        leaveDurationLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        year1Label = new javax.swing.JLabel();
        month1Label = new javax.swing.JLabel();
        date1Label = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        year2Label = new javax.swing.JLabel();
        month2Label = new javax.swing.JLabel();
        date2Label = new javax.swing.JLabel();
        year2CB = new javax.swing.JComboBox<>();
        month2CB = new javax.swing.JComboBox<>();
        day2CB = new javax.swing.JComboBox<>();
        dateFiledTF = new javax.swing.JTextField();
        dateFiledLabel = new javax.swing.JLabel();
        year1CB = new javax.swing.JComboBox<>();
        month1CB = new javax.swing.JComboBox<>();
        day1CB = new javax.swing.JComboBox<>();
        reasonTF = new javax.swing.JTextField();
        reasonLabel1 = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Sick Leave", "Vacation Leave", "Emergency Leave"
            }
        ));
        leaveTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(leaveTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, 635, 292));

        leaveDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        leaveDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));

        LeaveDetailsLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        LeaveDetailsLabel.setText("Leave Details");

        employeeNumberLabel.setText("Employee Number:");

        typeOfLeaveLabel.setText("Type of Leave:");

        leaveTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick Leave", "Vacation Leave", "Emergency Leave" }));

        numberOfDaysLabel.setText("Number of Days:");

        daysCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        daysCB.setEnabled(false);

        employeeNumberTF.setEditable(false);
        employeeNumberTF.setEnabled(false);

        lastNameLabel.setText("Last Name:");

        lastNameTF.setEditable(false);
        lastNameTF.setEnabled(false);

        firstNameLabel.setText("First Name:");

        firstNameTF.setEditable(false);
        firstNameTF.setEnabled(false);

        javax.swing.GroupLayout leaveDetailsPanelLayout = new javax.swing.GroupLayout(leaveDetailsPanel);
        leaveDetailsPanel.setLayout(leaveDetailsPanelLayout);
        leaveDetailsPanelLayout.setHorizontalGroup(
            leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeaveDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leaveDetailsPanelLayout.createSequentialGroup()
                        .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numberOfDaysLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeOfLeaveLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(leaveTypeCB, 0, 141, Short.MAX_VALUE)
                            .addComponent(daysCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeeNumberTF)
                            .addComponent(lastNameTF)
                            .addComponent(firstNameTF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leaveDetailsPanelLayout.setVerticalGroup(
            leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeaveDetailsLabel)
                .addGap(18, 18, 18)
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNumberLabel)
                    .addComponent(employeeNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOfLeaveLabel)
                    .addComponent(leaveTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaveDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daysCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfDaysLabel))
                .addGap(51, 51, 51))
        );

        getContentPane().add(leaveDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 300, 230));

        leaveDurationPanel.setBackground(new java.awt.Color(255, 255, 255));
        leaveDurationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 5));

        leaveDurationLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        leaveDurationLabel.setText("Leave Duration");

        startDateLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        startDateLabel.setText("Start Date:");

        year1Label.setText("Year:");

        month1Label.setText("Month:");

        date1Label.setText("Date:");

        endDateLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        endDateLabel.setText("End Date:");

        year2Label.setText("Year:");

        month2Label.setText("Month:");

        date2Label.setText("Date:");

        year2CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2026", "2027", " " }));

        month2CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        day2CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        dateFiledTF.setEnabled(false);

        dateFiledLabel.setText("Date Filed:");

        year1CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2026", "2027" }));

        month1CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        day1CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        reasonLabel1.setText("Reason:");

        javax.swing.GroupLayout leaveDurationPanelLayout = new javax.swing.GroupLayout(leaveDurationPanel);
        leaveDurationPanel.setLayout(leaveDurationPanelLayout);
        leaveDurationPanelLayout.setHorizontalGroup(
            leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                        .addComponent(leaveDurationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leaveDurationPanelLayout.createSequentialGroup()
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                        .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(year1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(month1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(year1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(month1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                                .addComponent(date1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(day1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                        .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(date2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(year2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(month2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(month2CB, 0, 1, Short.MAX_VALUE)
                                            .addComponent(day2CB, 0, 1, Short.MAX_VALUE)
                                            .addComponent(year2CB, 0, 1, Short.MAX_VALUE)))))
                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                .addComponent(dateFiledLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateFiledTF))
                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                .addComponent(reasonLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))))
        );
        leaveDurationPanelLayout.setVerticalGroup(
            leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leaveDurationLabel)
                .addGap(12, 12, 12)
                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateFiledLabel)
                    .addComponent(dateFiledTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                        .addComponent(startDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year1Label)
                            .addComponent(year1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month1Label)
                            .addComponent(month1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(date1Label)
                                    .addComponent(day1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(leaveDurationPanelLayout.createSequentialGroup()
                        .addComponent(endDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year2Label)
                            .addComponent(year2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month2Label)
                            .addComponent(month2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date2Label)
                            .addComponent(day2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(leaveDurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(leaveDurationPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 230));

        applyButton.setBackground(new java.awt.Color(204, 204, 204));
        applyButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        applyButton.setText("Apply");
        applyButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applybtn(evt);
            }
        });
        getContentPane().add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 104, 30));

        closeButton.setBackground(new java.awt.Color(204, 204, 204));
        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 94, 30));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Black and White Illustrated Custom Motorcycle Poster.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close
        dispose();
    }//GEN-LAST:event_Close

    private void applybtn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applybtn
                        
           Staff staff = new Staff();
           String filename = "Remaining_Leave.csv";

           // Get values from text fields and combo boxes
           String employeeNumber = employeeNumberTF.getText().trim();
           String lastName = lastNameTF.getText().trim();
           String firstName = firstNameTF.getText().trim();
           String reason = reasonTF.getText().trim();
           dateFiledTF.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));
           String fileDate = dateFiledTF.getText();
           String leaveType = leaveTypeCB.getSelectedItem().toString();

           // Get start and end dates from combo boxes
           String startDate = String.format("%02d/%02d/%s",
                   Integer.parseInt(month1CB.getSelectedItem().toString()),
                   Integer.parseInt(day1CB.getSelectedItem().toString()),
                   year1CB.getSelectedItem().toString());

           String endDate = String.format("%02d/%02d/%s",
                   Integer.parseInt(month2CB.getSelectedItem().toString()),
                   Integer.parseInt(day2CB.getSelectedItem().toString()),
                   year2CB.getSelectedItem().toString());

           // === VALIDATION ===
           if (employeeNumber.isEmpty() || lastName.isEmpty() || firstName.isEmpty() || reason.isEmpty()) {
               JOptionPane.showMessageDialog(this, "All fields must be filled out, including the reason.", "Input Error", JOptionPane.ERROR_MESSAGE);
               return; // Stop execution if any required field is empty
           }

           // Set values to the staff object AFTER validation
           staff.setEmployeeNumber(employeeNumber);
           staff.setLastName(lastName);
           staff.setFirstName(firstName);

           // Validate and calculate number of days
           String days;
           try {
               days = staff.validateLeaveDate(startDate, endDate);

               // Set the calculated number of days in daysCB
               daysCB.setSelectedItem(days); // Auto-populate calculated days

           } catch (IllegalArgumentException e) {
               JOptionPane.showMessageDialog(this, e.getMessage(), "Date Error", JOptionPane.ERROR_MESSAGE);
               return; // Stop execution if dates are invalid
           }

           try {
               // Check if leave is allowed
               if (staff.LeaveIsAllowed(filename, leaveType, days)) {
                   staff.ApplyLeave(filename, leaveType, days);
                   staff.createLeaveApplication(fileDate, leaveType, days, startDate, endDate, reason);

                   JOptionPane.showMessageDialog(this, "Leave Submitted Successfully!", "Leave Application", JOptionPane.INFORMATION_MESSAGE);

                   // Refresh leaveTable without clearing other fields
                   leaveTable.setModel(staff.leaveDetails(filename));

               } else {
                   JOptionPane.showMessageDialog(this, "Applied Leave Exceeds Remaining Leave!", "Leave Unallowed", JOptionPane.ERROR_MESSAGE);
               }
           } catch (IOException | CsvValidationException ex) {
               Logger.getLogger(LeaveFrame.class.getName()).log(Level.SEVERE, null, ex);
           }  
    }//GEN-LAST:event_applybtn

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveFrame().setVisible(true);
            }
        });
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LeaveDetailsLabel;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel date1Label;
    private javax.swing.JLabel date2Label;
    private javax.swing.JLabel dateFiledLabel;
    private javax.swing.JTextField dateFiledTF;
    private javax.swing.JComboBox<String> day1CB;
    private javax.swing.JComboBox<String> day2CB;
    private javax.swing.JComboBox<String> daysCB;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JTextField employeeNumberTF;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JPanel leaveDetailsPanel;
    private javax.swing.JLabel leaveDurationLabel;
    private javax.swing.JPanel leaveDurationPanel;
    private javax.swing.JTable leaveTable;
    private javax.swing.JComboBox<String> leaveTypeCB;
    private javax.swing.JComboBox<String> month1CB;
    private javax.swing.JLabel month1Label;
    private javax.swing.JComboBox<String> month2CB;
    private javax.swing.JLabel month2Label;
    private javax.swing.JLabel numberOfDaysLabel;
    private javax.swing.JLabel reasonLabel1;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel typeOfLeaveLabel;
    private javax.swing.JComboBox<String> year1CB;
    private javax.swing.JLabel year1Label;
    private javax.swing.JComboBox<String> year2CB;
    private javax.swing.JLabel year2Label;
    // End of variables declaration//GEN-END:variables
}
